Traceback (most recent call last):
  File "/home/kdyun/anaconda3/envs/decidiff/lib/python3.8/site-packages/ml_logger/__init__.py", line 231, in thunk
    results = fn(*(args or ARGS), **_KWARGS)
  File "/home/kdyun/workspace/decidiff/code/script/train.py", line 51, in main
    dataset = dataset_config()
  File "/home/kdyun/workspace/decidiff/code/diffuser/utils/config.py", line 65, in __call__
    instance = self._class(*args, **kwargs, **self._dict)
  File "/home/kdyun/workspace/decidiff/code/diffuser/datasets/sequence.py", line 44, in __init__
    self.normalize()
  File "/home/kdyun/workspace/decidiff/code/diffuser/datasets/sequence.py", line 56, in normalize
    normed = self.normalizer(array, key)
  File "/home/kdyun/workspace/decidiff/code/diffuser/datasets/normalization.py", line 38, in __call__
    return self.normalize(*args, **kwargs)
  File "/home/kdyun/workspace/decidiff/code/diffuser/datasets/normalization.py", line 41, in normalize
    return self.normalizers[key].normalize(x)
KeyError: 'actions'
